### ISSUE TITLE
Symmetric vs commutative

### ISSUE THREAD

**Issue by dimitarg** [fommil/fpmortals#47]
In "5.3 Objecty Things", where equal is introduced, it is said
```
commutative f1 === f2 implies f2 === f1
```
I know this is technically correct, since the equality equivalence relation is also a function `A -> A -> Bool`. I thought that when talking about relations (of equivalence) it is customary to say `symmetric` for this property, and I wanted to point this out.

It might be a cultural thing; most of the Maths books I've read are in Bulgarian. Feel free to disregard and close this at your discretion.

**Comment by fommil** [comment]
You're technically correct, which is the best kind of correct. This is the "symmetric property" but since it is associative, we can also say "commutative".

The scalaz law is called "commutative" and "non-commutative" is used many times later in the book, so I'm happy to stick with "commutative" here for consistency.

**Comment by dimitarg** [comment]
Got it, thanks!
