### ISSUE TITLE
Why does splitBy return an IList

### ISSUE THREAD

**Issue by DaniRey** [fommil/fpmortals#7]
In the chapter "##Foldable" you have an example using `splitBy`

{lang="text"}
~~~~~~~~
  scala> IList("foo", "bar", "bar", "faz", "gaz", "baz").splitBy(_.charAt(0))
  res = [(f, [foo]), (b, [bar, bar]), (f, [faz]), (g, [gaz]), (b, [baz])]
~~~~~~~~

Can you explain why this returns an IList of Tuples instead of a Map?

**Comment by fommil** [comment]
That would require an `A: Order`, which would limit the usefulness of the function.

But since `IMap` is not introduced until the next chapter, it would introduce a dependency cycle to have a digression at this point in the code. It already feels hacky that I needed to introduce `\/`, `\&/`, `\?/` and `IList` before the data type section... but they are easy to explain. `ITree` would mean explaining balanced trees.

**Comment by fommil** [comment]
I'm not I agree that a map would be better. An IList of tuples captures the structure just fine and retains order.

**Comment by DaniRey** [comment]
I see your point. I had a different use case in mind. I thought about creating a Map for lookup, while you probably have a List with grouping in mind.

**Comment by fommil** [comment]
if you want an IMap, and you have `Order[A]`, you can easily create one.
